name: CI/CD Pipeline

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      REACT_APP_API_URL: ${{secrets.REACT_APP_API_URL}}

    steps:
      - uses: actions/checkout@v3
      - name: Login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build docker image
        run: docker build --build-arg REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }} -t klarv/spotter-test-web .
      - name: Publish image to docker hub
        run: docker push klarv/spotter-test-web:latest

  deploy:
    needs: build
    runs-on: aws-ec2
    steps:
      - name: Pull image from docker hub
        run: docker pull klarv/spotter-test-web:latest
      - name: Delete old container
        run: docker rm -f react-app-container
      - name: Run docker container
        run: docker run -d -p 80:80 --name react-app-container klarv/spotter-test-web
